services:
  backend:
    image: ghcr.io/heriberto777/core_app-backend:latest
    container_name: core_app-backend
    restart: always
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 384M
        reservations:
          memory: 128M
    expose:
      - "3000"

  frontend:
    image: ghcr.io/heriberto777/core_app-frontend:latest
    container_name: core_app-frontend
    restart: always
    ports:
      - "8082:80"
    deploy:
      resources:
        limits:
          memory: 64M
    depends_on:
      - backend
